CompileFlags:
  Add:
    - --no-cuda-version-check
    - -Wno-unknown-warning-option
    - -D__clangd__
    - -std=c++2c
  Remove:
    - -forward-unknown-to-host-compiler
    - -expt-*
    - --expt-*
    - -gencode*
    - --generate-code*
    - -Xfatbin*
    - -arch=*
    - -rdc=*
    - -mno-*
InlayHints:
  ParameterNames: Yes
  DecucedTypes: Yes
